name: Send weekly update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 5 * * 0' # This will run at 5 AM UTC every Sunday

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.10' # Specify the Node.js version

        - name: Install dependencies
          run: npm ci

        - name: Run start script
          run: npm run start
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
